# Generated by Django 2.2.13 on 2021-06-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
