# Generated by Django 2.2.13 on 2021-06-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
