# Generated by Django 2.2.13 on 2021-06-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20210701_0215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Feedback',
        ),
    ]
